server {
    listen 80;
    server_name spacesneakers.store www.spacesneakers.store;

    location / {
        include proxy_params;
        proxy_pass http://unix:/var/www/sneakerspace/sneakerspace.sock;
    }

    location /static {
        alias /var/www/sneakerspace/assets;
    }

    location /uploads {
        alias /var/www/sneakerspace/backend/uploads;
    }
}
