"""Add is_trending, is_new_arrival to Product and is_homepage_banner to Offer

Revision ID: f6a6932f03f7
Revises: 70c335ddb61f
Create Date: 2026-05-28 16:15:04.413289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6a6932f03f7'
down_revision = '70c335ddb61f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_homepage_banner', sa.Boolean(), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_trending', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_new_arrival', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('is_new_arrival')
        batch_op.drop_column('is_trending')

    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.drop_column('is_homepage_banner')

    # ### end Alembic commands ###
